export const metadata = {
  title: 'Terms of Service - ChatPlay Mafia',
  description: 'Terms of Service for ChatPlay Mafia',
};

export default function Terms() {
  return (
    <div style={{ 
      maxWidth: '800px', 
      margin: '0 auto', 
      padding: '2rem',
      color: '#e0e0e0',
      background: '#1a1a1a',
      minHeight: '100vh',
      fontFamily: "'Courier New', monospace",
      lineHeight: '1.6'
    }}>
      <h1 style={{ 
        letterSpacing: '0.1em', 
        textAlign: 'center',
        borderBottom: '1px solid #333',
        paddingBottom: '1rem'
      }}>
        TERMS OF SERVICE
      </h1>
      
      <p style={{ color: '#888', fontSize: '0.875rem' }}>
        Last updated: April 26, 2026
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using ChatPlay Mafia, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        ChatPlay Mafia is an interactive role-playing game featuring AI-driven characters (NPCs) with whom players communicate. The game simulates a mafia-style narrative experience.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        <strong>Authentication:</strong> You must register and maintain accurate account information. You are responsible for maintaining the confidentiality of your authentication methods.
      </p>
      <p>
        <strong>One Account:</strong> Each user is limited to one account. Multiple accounts are not permitted.
      </p>
      <p>
        <strong>Age Requirement:</strong> You must be 18 years or older to create an account.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>
        You agree NOT to:
      </p>
      <ul>
        <li>Use the service for any unlawful purpose</li>
        <li>Attempt to hack, exploit, or interfere with the service</li>
        <li>Use automated bots or scripts without permission</li>
        <li>Harass, abuse, or threaten other users</li>
        <li>Attempt to extract or misuse AI prompts or game content</li>
        <li>Share your account or authentication credentials</li>
      </ul>

      <h2>5. Game Content</h2>
      <p>
        <strong>AI Content:</strong> Responses from NPCs are generated by AI and do not represent the views of ChatPlay Mafia.
      </p>
      <p>
        <strong>Your Content:</strong> Messages you send are used to generate game responses and may be stored for game functionality.
      </p>
      <p>
        <strong>Fictional Context:</strong> This is a fictional game. Real-world criminal activity is strictly prohibited.
      </p>

      <h2>6. Fees and Payments</h2>
      <p>
        Currently, the service is provided free of charge. Any future fees will be clearly communicated before you are charged.
      </p>

      <h2>7. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account at any time for violations of these terms or for any reason deemed necessary.
      </p>

      <h2>8. Disclaimer</h2>
      <p>
        THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE UNINTERRUPTED OR ERROR-FREE SERVICE.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, CHATPLAY MAFIA SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We may update these terms at any time. Continued use of the service after changes constitutes acceptance of new terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these terms?<br />
        Contact us at: <strong>legal@chatplay-mafia.com</strong>
      </p>

      <div style={{ 
        marginTop: '3rem', 
        paddingTop: '1rem', 
        borderTop: '1px solid #333',
        fontSize: '0.75rem',
        color: '#666'
      }}>
        <a href="/" style={{ color: '#888' }}>← Back to Game</a>
      </div>
    </div>
  );
}